// <auto-generated />
namespace JobBoardMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201703091932530_DbSetProjectDesigner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201703091932530_DbSetProjectDesigner));
        
        string IMigrationMetadata.Id
        {
            get { return "201704141648185_201703091932530_DbSetProjectDesigner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
